
github: [Atik203] # Updated to match your actual GitHub username
patreon: atik203 # Remove if you don't have a Patreon account
ko_fi: atik203 # Remove if you don't have a Ko-fi account
buy_me_a_coffee: atik203 # Replace with a single Buy Me a Coffee username
