nodeLinker: node-modules
enableGlobalCache: false
enableTelemetry: false
packageExtensions:
  "@scholar-flow/backend@*":
    dependencies:
      "@aws-sdk/client-s3": "^3.0.0"
      "@aws-sdk/s3-request-presigner": "^3.0.0"
      "multer": "^1.4.5-lts.2"
      "multer-s3": "^3.0.1"
      "sharp": "^0.34.3"
      "crypto-js": "^4.2.0"
  "@scholar-flow/frontend@*":
    dependencies:
      "react-dropzone": "^14.2.3"
  "react-window@*":
    peerDependencies:
      "react": ">=16.0.0"
      "react-dom": ">=16.0.0"
  "next-themes@*":
    peerDependencies:
      "react": ">=18.2.0 <20.0.0 || ^19.0.0"
      "react-dom": ">=18.2.0 <20.0.0 || ^19.0.0"
  "framer-motion@*":
    peerDependencies:
      "react": ">=18.0.0 || ^19.0.0"
      "react-dom": ">=18.0.0 || ^19.0.0"
  "next-auth@*":
    peerDependencies:
      "react": ">=18.0.0 || ^19.0.0"
      "react-dom": ">=18.0.0 || ^19.0.0"